stages:
  - pages


pages:
  stage: pages
  script:
    - wget https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz
    - tar -xvf node-v18.17.1-linux-x64.tar.xz
    - cd node-v18.17.1-linux-x64
    - export PATH=$PATH:`pwd`/bin
    # - node -v
    # - npm -v
  # script:
    - npm run gitlab
    # - gitlab-pages
  only:
    - main  # 在 main 分支上觸發 CI/CD
