stages:
  - build
  - deploy

build:
  stage: build
  script:
    - sudo apt update
    - sudo apt install nodejs npm
    
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r dist/* .public
    - mv .public pages
  artifacts:
    paths:
      - pages
  only:
    - main
