stages:
  - build
  - deploy

build:
  stage: build
  script:
    - wget https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz
    - tar -xvf node-v18.17.1-linux-x64.tar.xz
    - cd node-v18.17.1-linux-x64
    - export PATH=$PATH:`pwd`/bin
    # - node -v
    # - npm -v
    


    
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r dist/* .public
    - mv .public pages
  artifacts:
    paths:
      - pages
  only:
    - main
